trigger:
  branches:
    include:
      - main

variables:
  - name: majorMinorVersion
    value: 0.0
  - name: semanticVersion
    value: $[counter(variables['majorMinorVersion'], 0)]
  - group: ApiKeys
  
name: $(majorMinorVersion).$(semanticVersion)


stages:
  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - stage: Validation
        displayName: Validate 'Build.Reason'
        jobs:
          - job: build_test
            steps:
              - task: DotNetCoreCLI@2
                displayName: Build
                inputs:
                  command: build
                  workingDirectory: src/GraphQL.Filters
                  versioningScheme: byBuildNumber
                  arguments: --configuration Release -p:Version=$(majorMinorVersion).$(semanticVersion)
                  configuration: Release
              - task: DotNetCoreCLI@2
                displayName: UnitTest
                inputs:
                  command: test
                  workingDirectory: src/GraphQL.Filters
                  arguments: --configuration Release --no-build --no-restore
