
name: Build Graphql Filters

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with: 
        persist-credentials: false
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/GraphQL.Filters
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: ./src/GraphQL.Filters
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal --collect "XPlat Code Coverage" --results-directory coverage
      working-directory: ./src/GraphQL.Filters
    - name: Make SpecFlow Documentation
      working-directory: ./src/GraphQL.Filters/GraphQL.Filters.Tests
      run: |
        dotnet new tool-manifest
        dotnet tool install SpecFlow.Plus.LivingDoc.CLI
        dotnet livingdoc livingdoc test-assembly ./bin/Release/net6.0/GraphQL.Filters.Tests.dll -t ./bin/Release/net6.0/TestExecution.json --output ../../../docs/GraphQL.Filters.Specflow.html
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: ./src/GraphQL.Filters/coverage/**/coverage.cobertura.xml
        targetdir: ./docs
        reporttypes: MarkdownSummaryGithub
    - uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "./docs/"
        update-pull-request-title-and-body: false
    # - name: push docs
    #   run: |
    #     ls -l ./docs/*
    #     git config --global user.email "pr@titaniumt.nl"
    #     git config --global user.name "AutomatedAction"
    #     git add -A ./docs/*
    #     git pull origin HEAD:$GITHUB_HEAD_REF
    #     git commit -m documentation
    #     git push origin HEAD:$GITHUB_HEAD_REF
    
     
