
name: Build Graphql Filters

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/GraphQL.Filters
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: ./src/GraphQL.Filters
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal --collect "XPlat Code Coverage" --results-directory coverage
      working-directory: ./src/GraphQL.Filters
    - name: Make SpecFlow Documentation
      working-directory: ./src/GraphQL.Filters/GraphQL.Filters.Tests
      run: |
        dotnet new tool-manifest
        dotnet tool install SpecFlow.Plus.LivingDoc.CLI
        dotnet livingdoc livingdoc test-assembly ./bin/Release/net6.0/GraphQL.Filters.Tests.dll -t ./bin/Release/net6.0/TestExecution.json --output ../../../docs/GraphQL.Filters.Specflow.html
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: ./src/GraphQL.Filters/coverage/**/coverage.cobertura.xml
        targetdir: ./docs
        reporttypes: MarkdownSummaryGithub
    - name: push docs
      run: |
        ls -l ./docs/*
        git config --global user.email "pr@titaniumt.nl"
        git config --global user.name "AutomatedAction"
        git add -A ./docs/*
        git commit -m documentation
        git push origin HEAD:$GITHUB_REF
    
     
