
name: Build Graphql Filters

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/GraphQL.Filters
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: ./src/GraphQL.Filters
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal --collect "XPlat Code Coverage" --results-directory coverage
      working-directory: ./src/GraphQL.Filters
    - name: Make SpecFlow Documentation
      working-directory: ./src/GraphQL.Filters/GraphQL.Filters.Tests
      run: |
        dotnet new tool-manifest
        dotnet tool install SpecFlow.Plus.LivingDoc.CLI
        dotnet livingdoc livingdoc test-assembly ./bin/Release/net6.0/GraphQL.Filters.Tests.dll -t ./bin/Release/net6.0/TestExecution.json --output GraphQL.Filters.Specflow.html
    - name: Produce the coverage report
      uses: insightsengineering/coverage-action@v2
      with:
        path: ./src/GraphQL.Filters/coverage/**/coverage.cobertura.xml
        threshold: 80.123
        fail: true
        publish: true
        diff: true
        diff-branch: main
        diff-storage: _xml_coverage_reports
        coverage-summary-title: "Code Coverage Summary"
  
     
