
name: Build Graphql Filters

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/GraphQL.Filters
    - name: Build
      run: dotnet build --no-restore -c Release
      working-directory: ./src/GraphQL.Filters
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal --collect "XPlat Code Coverage" --results-directory .coverage
      working-directory: ./src/GraphQL.Filters
    - name: Make SpecFlow Documentation
      uses: cryptic-wizard/run-specflow-tests@v1.3.2
      with:
        test-assembly-path: ./src/GraphQL.Filters/GraphQL.Filters.Tests/bin/Release/net8.0/
        test-assembly-dll: GraphQL.Filters.Tests.dll
        framework: net8.0
        no-build: true
        output-html: TestOutput.html
        upload-artifact: true
